### ISSUE TITLE
About training 

### ISSUE THREAD

**Issue by ccssw1** [cxjyxxme/deep-online-video-stabilization#1]
There is no'data_video/resnet_v2_50.ckpt'in the folder. Could you send it out?

**Comment by cxjyxxme** [comment]
You can download it from here: http://download.tensorflow.org/models/resnet_v2_50_2017_04_14.tar.gz

**Comment by chenyuanpengcyp** [comment]
@ccssw1  Hello, do you run the code?   If you run it, I want to know how the data is processed.
