### ISSUE TITLE
About optical flow in the dataset

### ISSUE THREAD

**Issue by MurrayC7** [cxjyxxme/deep-online-video-stabilization#4]
Hi, 
Thank you for your nice work. I'm confused about the flow in your dataset. It's mentioned in the README that you set the optical flow to 0, but I found these values in the tfrecord file (train/0.tfrecord) and other files are similar. It seems the optical flow is normalized to be in the range [-1, 1]. Are these values correct?  
Or, should I recompute it and modify the tfrecord file?

feature {
    key: "flow"
    value {
      float_list {
        value: -1.0
        value: -1.0
        value: -0.99609375
        value: -1.0
        value: -0.9921875
        value: -1.0
        value: -0.98828125
        ..........
        value: 0.984375
        value: 0.9930555820465088
        value: 0.98828125
        value: 0.9930555820465088
        value: 0.9921875
        value: 0.9930555820465088
        value: 0.99609375
        value: 0.9930555820465088
      }
    }
  }

I would appreciate it if you could tell me how to deal with this flow information :)

Yours,
Murray

**Comment by cxjyxxme** [comment]
Hi, set flow to 0 is done during generating tfrecord datas, you can run the training scripts to train the net directly.

**Comment by MurrayC7** [comment]
Thanks for your attention! 
That means these values of optical flow is correct, and I don't need to modify the tfrecord files, right?

**Comment by cxjyxxme** [comment]
Yeah

**Comment by MurrayC7** [comment]
Thanks :)

**Comment by chenyuanpengcyp** [comment]
@MurrayC7 Hello, do you run the code? If you run it, I want to know how the data is processed.
